version: '3.7'
volumes:
  database_data:
    driver: local
services:
  db:
    image: 'postgres:latest' # use latest official postgres version
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo
    volumes:
      - database_data:/var/lib/postgresql/data
  web:
    build: .
    image: marcelodsales/go-gin-gorm-pg
    ports:
      - '8080:8080'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - database.env  # configure postgres
    links:
      - db